export const products=[
    {
        id:1,
        image:'https://zandokh.com/image/cache/catalog/products/2024-06/5132312009/T-Shirt%20(9)-cr-450x672.jpg',
        category:'Man',
        regular_price:0,
        sale_price:22.5,
        title:'Regular T-Shirts',
        description:'ធំៗអស់ហើយ Research មើលខ្លួនឯងខ្លះទៅកុំចាំតែគេរៀបរាប់ពេក',
        views:340,
        size:'M,L,XL',
        color:'Black,Blue',
    },
    {
        id:2,
        image:'https://zandokh.com/image/cache/catalog/products/2024-09/5152312018/T-Shirt%20(8)-cr-450x672.jpg',
        category:'Man',
        regular_price:30,
        sale_price:22.59,
        title:'Sport Life T-Shirts',
        description:'Sport Life T-Shirts',
        views:99,
        size:'M,L,XL',
        color:'White,Gray',
    },
    {
        id:3,
        image:'https://zandokh.com/image/cache/catalog/products/2024-06/5252312015/T-Shirt%20(13)-cr-450x672.jpg',
        category:'Woman',
        regular_price:18,
        sale_price:12.5,
        title:'Sport Lift T-Shirts',
        description:'Sport Lift T-Shirts',
        views:20,
        size:'M,L,XL',
        color:'Pink',
    },
    {
        id:4,
        image:'https://zandokh.com/image/cache/catalog/products/2024-12/3222409490/Mini%20Dress%20(1)-cr-450x672.jpg',
        category:'Woman',
        regular_price:0,
        sale_price:18.5,
        title:'Mini Dress',
        description:'Mini Dress',
        views:31,
        size:'M,L,XL',
        color:'Black',
    },
    {
        id:5,
        image:'https://zandokh.com/image/cache/catalog/products/2024-08/5152405105/Sport-Life-Sweatshirt%20(3)-cr-450x672.jpg',
        category:'Boy',
        regular_price:15,
        sale_price:9,
        title:'Sport Life Sweatshirt',
        description:'Sport Life Sweatshirt',
        views:19,
        size:'S,M',
        color:'Black',
    },
    {
        id:6,
        image:'https://zandokh.com/image/cache/catalog/products/2024-07/5152405084/Shorts%20(3)-cr-450x672.jpg',
        category:'Boy',
        regular_price:0,
        sale_price:22.5,
        title:'Sport Life Knitted Quarter',
        description:'Sport Life Knitted Quarter',
        views:7,
        size:'S,M',
        color:'Black',
    },
    {
        id:7,
        image:'https://zandokh.com/image/cache/catalog/products/2024-09/1322407102/T-Shirt%20(8)-cr-450x672.jpg',
        category:'Boy',
        regular_price:0,
        sale_price:18,
        title:'T-Shirt With Print',
        description:'T-Shirt With Print',
        views:28,
        size:'S,M,L',
        color:'Yellow,White',
    },
    {
        id:8,
        image:'https://zandokh.com/image/cache/catalog/products/2024-02/1422312202/Jeans%20(7)-cr-450x672.jpg',
        category:'Girl',
        regular_price:0,
        sale_price:16.5,
        title:'Slim Fit Jeans',
        description:'Slim Fit Jeans',
        views:19,
        size:'S,M',
        color:'Gray',
    },
    {
        id:9,
        image:'https://zandokh.com/image/cache/catalog/products/2024-08/5252405050/Trousers%20(3)-cr-450x672.jpg',
        category:'Girl',
        regular_price:15,
        sale_price:7.50,
        title:'Sport Life Capri Pants',
        description:'Sport Life Capri Pants',
        views:60,
        size:'M,L',
        color:'Black',
    },
    {
        id:10,
        image:'https://zandokh.com/image/cache/catalog/products/2024-07/1422403230/T-Shirt%20(5)-cr-450x672.jpg',
        category:'Girl',
        regular_price:0,
        sale_price:7.80,
        title:'Blouse With Pockets',
        description:'Blouse With Pockets',
        views:35,
        size:'S,M,L',
        color:'Brown',
    },
    {
        id:11,
        image:'https://zandokh.com/image/cache/catalog/products/2024-05/1222404426/T-Shirt-With-Print%20(3)-cr-450x672.jpg',
        category:'Woman',
        regular_price:0,
        sale_price:21.5,
        title:'T-Shirt With Print',
        description:'T-Shirt With Print',
        views:45,
        size:'M,L,XL',
        color:'Green',
    },
    {
        id:12,
        image:'https://zandokh.com/image/cache/catalog/products/2024-04/1222403253/T-Shirt%20(3)-cr-450x672.jpg',
        category:'Woman',
        regular_price:0,
        sale_price:22.5,
        title:'Regular T-Shirt',
        description:'..........',
        views:47,
        size:'M,L,XL',
        color:'Brown,Pink',
    },
    {
        id:13,
        image:'https://zandokh.com/image/catalog/products/2024-12/1222412905/IMG_2868.jpg',
        category:'Woman',
        regular_price:0,
        sale_price:23.59,
        title:'Tiered Maxi Skirt',
        description:'Tiered Maxi Skirt',
        views:27,
        size:'XS,S,M,L',
        color:'White,Blue',
    },
    {
        id:14,
        image:'https://zandokh.com/image/cache/catalog/products/2024-12/2122411917/IMG_0584-cr-450x672.jpg',
        category:'Man',
        regular_price:0,
        sale_price:22.5,
        title:'Loose Fit T-Shirts With Printed',
        description:'ធំៗអស់ហើយ Research មើលខ្លួនឯងខ្លះទៅកុំចាំតែគេរៀបរាប់ពេក',
        views:77,
        size:'S,M,L,XL,XXL',
        color:'Black,Navy Blue',
    },
    {
        id:15,
        image:'https://zandokh.com/image/cache/catalog/products/2024-12/3222407394/IMG_0673-cr-450x672.jpg',
        category:'Woman',
        regular_price:0,
        sale_price:45.56,
        title:'Low Waist Dress',
        description:'Low waist dress featuring sleeveless with tie detail and back zipper-up fastening',
        views:97,
        size:'S,M,L',
        color:'Blue,Ivory',
    },
    {
        id:16,
        image:'https://zandokh.com/image/cache/catalog/products/2024-09/1322407099/T-Shirt%20(8)-cr-450x672.jpg',
        category:'Boy',
        regular_price:0,
        sale_price:6.26,
        title:'T-Shirt With Pocket',
        description:'T-Shirt With Pocket',
        views:41,
        size:'M,L,XL',
        color:'Gray,White',
    },
    {
        id:17,
        image:'https://zandokh.com/image/cache/catalog/products/2023-12/1422311202/Sweatshirt%20(4)-cr-450x672.jpg',
        category:'Girl',
        regular_price:0,
        sale_price:1.59,
        title:'Sweater Tank Top',
        description:'Sweater Tank Top',
        views:7,
        size:'M,L,XL',
        color:'Yellow,White',
    },
    {
        id:18,
        image:'https://zandokh.com/image/cache/catalog/products/2024-12/3222407406/IMG_0204-cr-450x672.jpg',
        category:'Woman',
        regular_price:0,
        sale_price:22.5,
        title:'Relaxed Cropped Shirts',
        description:'Relaxed Cropped Shirts',
        views:90,
        size:'XS,S,M,',
        color:'Olive Green,Beige',
    },
    {
        id:19,
        image:'https://zandokh.com/image/catalog/products/2023-12/1322311043/Puffer-jacket%20(4).jpg',
        category:'Girl',
        regular_price:0,
        sale_price:5.28,
        title:'Puffer Hoodie Jacket',
        description:'Puffer Hoodie Jacket',
        views:40,
        size:'M,L,XL',
        color:'Ivory',
    },
    {
        id:20,
        image:'https://zandokh.com/image/cache/catalog/products/2024-12/1122411648/IMG_0086-cr-450x672.jpg',
        category:'Man',
        regular_price:0,
        sale_price:18.59,
        title:'Relaxed Fit Shirtst',
        description:'Relaxed Fit Shirts',
        views:39,
        size:'S,M,L,XL',
        color:'Black,Ivory',
    },
    {
        id:21,
        image:'https://zandokh.com/image/catalog/products/2024-12/21224111024/IMG_1954.jpg',
        category:'Man',
        regular_price:0,
        sale_price:8.59,
        title:'Regular T-Shirts',
        description:'Regular T-Shirts',
        views:399,
        size:'S,M,L,XL',
        color:'Brown,Ivory,Blue,Black',
    },
    {
        id:22,
        image:'https://zandokh.com/image/catalog/products/2024-12/2122408805/IMG_2248.jpg',
        category:'Man',
        regular_price:0,
        sale_price:8.99,
        title:'Regular Fit Shirtst',
        description:'Regular Fit Shirts',
        views:39,
        size:'S,M,L,XL',
        color:'Black',
    },
];